AWSTemplateFormatVersion: 2010-09-09
# This CloudFormation template deploys a EC2 / SG / ASG / ELB.
Resources:
  PublicInstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Public Instances
      VpcId: !ImportValue 'kong-demo-vpc-KongVPCID'
      GroupName: KongDemo-PublicInstanceSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: KongDemo

  PrivateInstanceSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Private Instances
      VpcId: !ImportValue 'kong-demo-vpc-KongVPCID'
      GroupName: KongDemo-PrivateInstanceSG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: KongDemo

# commented as public instance can't get stabilized in smp-sandbox accnt- seems sthing accnt specific as works in eepairing accnt.
#  PublicInstance:
#    Type: AWS::EC2::Instance
#    Properties:
#      SubnetId: !ImportValue 'kong-demo-vpc-PublicSubnetAID'
#      ImageId: ami-0c4c4bd6cf0c5fe52
#      InstanceType: t2.micro
#      KeyName: smp-rohit                # this has to be created manually not via CF.
#      SecurityGroupIds:
#        - !Ref PublicInstanceSG
#      UserData:
#        Fn::Base64:
#          !Sub |
#          #!/bin/bash
#          echo "hello"
#          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
#          sudo systemctl start amazon-ssm-agent
#          sudo systemctl enable amazon-ssm-agent

  PrivateInstance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !ImportValue 'kong-demo-vpc-PrivateSubnetAID'
      ImageId: ami-0c4c4bd6cf0c5fe52
      InstanceType: t2.micro
      KeyName: smp-rohit                 # this has to be created manually not via CF.
      SecurityGroupIds:
        - !Ref PrivateInstanceSG
      UserData:
        Fn::Base64:
          !Sub |
          #!/bin/bash
          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
          sudo systemctl start amazon-ssm-agent
          sudo systemctl enable amazon-ssm-agent
          #################################################################
          # EFS mount command
          #sudo mkdir /efs
          #sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-03bdeac99bc039865.efs.eu-central-1.amazonaws.com:/ /efs
          #################################################################
          # to check o/p in URL(I used ELB as public IP on EC2 can't sustain in bcg sandbox)
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
      IamInstanceProfile: jenkins-master-role-prod-instance-profile   # added to make ssm connect work for ssh


########################################################################################################################

## EFS Setup: Another EC2 in diff AZ(subnet); EFS; and then mount it to both EC2s(regular and new)
#
#  PrivateInstanceEFSSetup:
#    Type: AWS::EC2::Instance
#    Properties:
#      SubnetId: !ImportValue 'kong-demo-vpc-PrivateSubnetBID'
#      ImageId: ami-0c4c4bd6cf0c5fe52
#      InstanceType: t2.micro
#      KeyName: smp-rohit                 # this has to be created manually not via CF.
#      SecurityGroupIds:
#        - !Ref PrivateInstanceSG
#      UserData:
#        Fn::Base64:
#          !Sub |
#          #!/bin/bash
#          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
#          sudo systemctl start amazon-ssm-agent
#          sudo systemctl enable amazon-ssm-agent
#          # EFS mount command
#          sudo mkdir /efs
#          sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport fs-03bdeac99bc039865.efs.eu-central-1.amazonaws.com:/ /efs
#      IamInstanceProfile: jenkins-master-role-prod-instance-profile
#
#  EFSVolume:
#    Type: AWS::EFS::FileSystem
#    Properties:
#      Encrypted: true
#      PerformanceMode: generalPurpose
#      ThroughputMode: elastic
#
#  EFSMountTargetSecurityGroup:
#    Type: 'AWS::EC2::SecurityGroup'
#    Properties:
#      GroupDescription: Security Group for EFS Mount Target
#      VpcId: !ImportValue 'kong-demo-vpc-KongVPCID'
#      GroupName: KongDemo-EFSMountTargetSG
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 2049                # this port should be whitelisted to connect to efs(nfs). This is default NFS port.
#          ToPort: 2049
#          CidrIp: 0.0.0.0/0
#
## We need mount targets in all the AZs(subnets) in which EC2s are going to use this EFS
#  EFSMountTargetSubnetA:
#    Type: AWS::EFS::MountTarget
#    Properties:
#      FileSystemId:
#        Ref: "EFSVolume"
#      SubnetId: !ImportValue 'kong-demo-vpc-PrivateSubnetAID'
#      SecurityGroups:
#        - Ref: "EFSMountTargetSecurityGroup"
#
#  EFSMountTargetSubnetB:
#    Type: AWS::EFS::MountTarget
#    Properties:
#      FileSystemId:
#        Ref: "EFSVolume"
#      SubnetId: !ImportValue 'kong-demo-vpc-PrivateSubnetBID'
#      SecurityGroups:
#        - Ref: "EFSMountTargetSecurityGroup"
#
## as we don't have mounttarget in subnet c so ec2s in eu-central-1c can't use this EFS.

########################################################################################################################



